INFO:2025-09-12 21:59:19,879:MainThread:Dhan.py  started system
INFO:2025-09-12 21:59:19,880:MainThread:STARTED THE PROGRAM
ERROR:2025-09-12 21:59:24,619:MainThread:Error at Gettting balance as {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 365, in get_balance
    raise Exception(response)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 21:59:24,674:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 21:59:26,873:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 525, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 21:59:26,935:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 21:59:27,001:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-12 22:04:52,691:MainThread:Dhan.py  started system
INFO:2025-09-12 22:04:52,691:MainThread:STARTED THE PROGRAM
ERROR:2025-09-12 22:04:54,252:MainThread:Error at Getting balance as {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 365, in get_balance
    raise Exception(response)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 22:04:54,282:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 22:04:56,378:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 525, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 22:04:56,424:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 22:04:56,459:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-12 22:05:46,327:MainThread:Dhan.py  started system
INFO:2025-09-12 22:05:46,327:MainThread:STARTED THE PROGRAM
ERROR:2025-09-12 22:05:48,012:MainThread:Error at Getting balance as {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 365, in get_balance
    raise Exception(response)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 22:05:48,043:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 22:05:50,161:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 525, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 22:05:50,207:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 22:05:50,240:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-12 22:07:21,028:MainThread:Dhan.py  started system
INFO:2025-09-12 22:07:21,028:MainThread:STARTED THE PROGRAM
ERROR:2025-09-12 22:07:22,632:MainThread:Error at Getting balance as {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 365, in get_balance
    raise Exception(response)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 22:07:22,659:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 22:07:24,745:MainThread:Exception in Getting OHLC data as [AUTH-ERROR] Authentication failed. Please check your ACCESS_TOKEN in config.py. Error details: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 527, in get_intraday_data
    raise Exception(f"[AUTH-ERROR] Authentication failed. Please check your ACCESS_TOKEN in config.py. Error details: {ohlc}")
Exception: [AUTH-ERROR] Authentication failed. Please check your ACCESS_TOKEN in config.py. Error details: {'status': 'failure', 'remarks': {'error_code': 'DH-906', 'error_type': 'Order_Error', 'error_message': 'Invalid Token'}, 'data': {'errorType': 'Order_Error', 'errorCode': 'DH-906', 'errorMessage': 'Invalid Token'}}
ERROR:2025-09-12 22:07:24,787:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-12 22:07:24,820:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
